[build]
    functions = "functions/stripe-charge"
    command = "npm run build"
    publish = "build"

[build.environment]
    NODE_ENV="production"

[context.production]
  publish = "build/"
  command = "npm run build"
  environment = { NODE_ENV = "production" }